MvcClient/Models/Pill.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MvcClient.Models
{
    public class Pill
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Pharmacy { get; set; }
        public decimal Price { get; set; }
    }
}

MvcClient/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcClient.Controllers
{
    public class ErrorController : Controller
    {        
        [AllowAnonymous]
        [Route("Error")]
        public IActionResult Error()
        {
            var exceptionHandlerPathFeature = 
                HttpContext.Features.Get<IExceptionHandlerPathFeature>();

            ViewBag.ExceptionMessage = exceptionHandlerPathFeature.Error.Message;

            return View("Error");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

MvcClient/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace MvcClient.Controllers
{
    public class HomeController: Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public async Task<IActionResult> UserInfo()
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");
            var idToken = await HttpContext.GetTokenAsync("id_token");
            var refreshToken = await HttpContext.GetTokenAsync("refresh_token");

            var _accessToken = new JwtSecurityTokenHandler().ReadJwtToken(accessToken);
            var _idToken = new JwtSecurityTokenHandler().ReadJwtToken(idToken);

            var claim = HttpContext.User.Claims.ToList();

            var userName = claim.Find(x => x.Type == "name");
            var userRole = claim.Find(x => x.Type == ClaimTypes.Role);

            ViewData["UserName"] = userName?.Value;
            ViewData["UserRole"] = userRole?.Value;

            return View("UserInfo");
        }

        public IActionResult Logout()
        {
            return SignOut("Cookie", "oidc");
        }

        public IActionResult Login()
        {
            return RedirectToAction("UserInfo");
        }
    }
}

MvcClient/Controllers/PharmacyInfoController.cs
using IdentityModel.Client;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MvcClient.Models;
using MvcClient.Services;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace MvcClient.Controllers
{
    [Authorize]
    public class PharmacyInfoController : Controller
    {
        private readonly ITokenService _tokenService;
        private readonly IHttpClientFactory _httpClientFactory;

        public PharmacyInfoController(ITokenService tokenService, IHttpClientFactory httpClientFactory)
        {
            _tokenService = tokenService;
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> Index()
        {
            using var httpClient = _httpClientFactory.CreateClient();

            //var accessToken = await _tokenService.GetToken("identityserver");
            var accessToken = await HttpContext.GetTokenAsync("access_token");
            httpClient.SetBearerToken(accessToken);

            var result = await httpClient.GetAsync("https://localhost:44340/api/pill/getPills");
            if(result.IsSuccessStatusCode)
            {
                var model = await result.Content.ReadAsStringAsync();
                var data = JsonConvert.DeserializeObject<List<Pill>>(model);

                return View(data);
            } 
            else
            {
                throw new Exception("Unable to get content");
            }
        }

        [Authorize(Roles = "Admin")]
        public IActionResult AdminAccess()
        {
            return View();
        }
    }
}

MvcClient/Views/Home/Index.cshtml
<div class="container mt-5">
    <h1 class="mb-3 mt-3 ">Home Page</h1>

    @if (User.Identity.IsAuthenticated)
    {
        <p>
            You are able to see user information
        </p>
    }
    else
    {
        <p>
            You need to login
        </p>
    }
</div>

MvcClient/Views/Home/UserInfo.cshtml
<div class="container mt-5">
    <h1 class="mb-3 mt-3">User Info</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">UserName</th>
                <th scope="col">User Role</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@ViewData["UserName"]</td>
                <td>@ViewData["UserRole"]</td>
            </tr>
        </tbody>
    </table>
</div>

MvcClient/Views/PharmacyInfo/AdminAccess.cshtml
<div class="container mt-3">
    <h1>Admin Access</h1>
    <h2>Congrats! You can see this page.</h2>
</div>

MvcClient/Views/PharmacyInfo/Index.cshtml
@model List<Pill>

<div class="container mt-5">
    <h1 class="mb-3 mt-3 ">Info Page</h1>
    
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Pharmacy</th>
                <th scope="col">Price</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Pharmacy</td>
                    <td>@item.Price</td>
                </tr>
            }
        </tbody>
    </table>
</div>

MvcClient/Views/Shared/AccessDenied.cshtml
<div>
    
</div>

MvcClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
</head>
<body>
    <nav class="py-2 bg-light border-bottom">
        <div class="container d-flex flex-wrap">
            <a class="navbar-brand link-dark" asp-controller="Home" asp-action="Index">Application</a>

            <ul class="nav me-auto">

                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="nav-link px-2 link-dark" aria-current="page" asp-controller="Home" asp-action="UserInfo">User Info</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-2 link-dark" aria-current="page" asp-controller="PharmacyInfo" asp-action="Index">Pharmacy Info</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-2 link-danger" aria-current="page" asp-controller="PharmacyInfo" asp-action="AdminAccess">Admin Access</a>
                    </li>
                }

            </ul>

            <ul class="nav">
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="btn btn-outline-danger" asp-action="Logout" asp-controller="Home">Logout</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="btn btn-outline-success" asp-action="Login" asp-controller="Home">Login</a>
                    </li>
                }

            </ul>
        </div>
    </nav>

    <div>
        @RenderBody()
    </div>

    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>

</body>
</html>